// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKD280p1ZH5fugpscWMtBRT9XASsan-F0',
    appId: '1:741793841757:web:d2b82ea060bef0568783b4',
    messagingSenderId: '741793841757',
    projectId: 'study-app-acef1',
    authDomain: 'study-app-acef1.firebaseapp.com',
    storageBucket: 'study-app-acef1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vcdixHObenBK6Bq42yIRpMtLLm0ykcM',
    appId: '1:741793841757:android:b8fc41d9fe02afd78783b4',
    messagingSenderId: '741793841757',
    projectId: 'study-app-acef1',
    storageBucket: 'study-app-acef1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKCwLrq2b8nmi7d41UMYkJ6rtIPbv43xA',
    appId: '1:741793841757:ios:8fa72b0c79488dda8783b4',
    messagingSenderId: '741793841757',
    projectId: 'study-app-acef1',
    storageBucket: 'study-app-acef1.appspot.com',
    iosClientId: '741793841757-ljteo0gvvv25e7ag2id2sv6la2lu92qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myStudyApp',
  );
}
